FROM client as build-stage
# A imagem de prod utiliza como base a imagem de desenvolvimento do client
RUN yarn build

FROM nginx:stable-alpine as production-stage
# Os artefatos estáticos gerados são copiados para serem servidos pelo nginx
COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "'daemon off;'"]