matrix:
  include:
    - name: Code Analysis
      stage: Static Analysis
      addons:
        sonarcloud:
          organization: "yoshida-eduardo"
          token:
            secure: "QS2P0wYVLcbuMAbO4ng+Rz47RlE136ZWLvxNZvEd8GBGjAhX66gM+naOfK2RugshDc9eY+U7SMH3TWXZ7PX9v07UhNt9YkE18RNyjSPes2SJhmGmxZ/iDmFFeQ6x0aumKS7lTfNwVRm+f77e7IzRCfw73YW3+CmnBf+AHD23D1YDOf8Y3bx6SFJEiYQmkQLj1jXLXRxc1BWTqGpeY1b1xpxQXaLZBRPxoS56hA9j9/WUSneLHSRQ7lRhDOkP9QcFyadF+mdRoyY1mAcN+DoC/IOyiuWJp57RRbXlmlN4y7k/dWjFwcbm/L1h45lZFGSIfJ3WcC0eUUXUfAFwTpWZi+sdm7PUzroWZM7S5qQOdJhyDVSzqMSViTGCgVM3fDMlVY8Emoimw7jVYVKYuV90XOPPxp0iZ6pM11uq8yWwXXHEbACtaUCw9EC2KJZhySqTHmfeyYvkIL54yG+WEZmnfrwJbQAQtDOM/bPVPAk8QGWqF3FQqRI3qHoBhBSQ12zwMTgn9h5aQ94jVACUPv1ustwBiPZsu46Tzv+OsySWXyHghSmYoTgwHPVyFKDqqk7VmnWkckHNi/p8EvU3+dUYV8cY1rrhkW2FVvl0qJg7jfRs5AKMywzWgSc40A9N4jwvgqInkOktK1oxL5aEIx4l1V+jJuPezzUdRg/Amf8cnWk="
      script:
        - sonar-scanner

    - name: Api Build
      stage: Build
      language: generic
      services:
        - postgresql
      env: 
        - REGEX='^(api\/|.travis.yml)'
        - DB_USER=postgres
      before_install:
        - git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE $REGEX || exit 0
      before_script:
        - psql -c 'create database api_test;' -U postgres
      install:
        - docker build -q -t api -f ./api/Dockerfile ./api
      script:
        - docker run api rake db:setup RAILS_ENV=test
        - docker run --env DB_HOST=localhost --env POSTGRES_USER=$DB_USER --env POSTGRES_PASSWORD="" api bundle exec rails test

    - name: Client Build
      stage: Build
      language: generic
      services:
        - docker
      env: 
        - REGEX='^(client\/|.travis.yml)'
      before_install:
        - git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE $REGEX || exit 0
      install:
        - docker build -q -t client -f ./client/Dockerfile ./client
      script:
        - docker run client yarn test:unit
