matrix:
  include:
    - name: Api Build
      stage: Build
      language: generic
      services:
        - postgresql
      env: 
        - REGEX='^(api\/|.travis.yml)'
        - DB_USER=postgres
      before_install:
        - git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE $REGEX || exit 0
      before_script:
        - psql -c 'create database api_test;' -U postgres
      install:
        - docker build -q -t api -f ./api/Dockerfile ./api
      script:
        - docker run api 
        - docker run  --env POSTGRES_USER=$DB_USER --env POSTGRES_PASSWORD="" api bundle exec rails test RAILS_ENV=test

    - name: Client Build
      stage: Build
      language: generic
      services:
        - docker
      env: 
        - REGEX='^(client\/|.travis.yml)'
      before_install:
        - git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE $REGEX || exit 0
      install:
        - docker build -q -t client -f ./client/Dockerfile ./client
      script:
        - docker run client yarn test:unit

    - name: Code Analysis
      stage: Static Analysis
      addons:
        sonarcloud:
          organization: "yoshida-eduardo"
          token:
            secure: $SONAR_KEY
      script:
        - sonar-scanner
