matrix:
  include:
    - name: Code Analysis
      stage: Static Analysis
      addons:
        sonarcloud:
          organization: "yoshida-eduardo"
          token:
            secure: $SONAR_KEY
      script:
        - sonar-scanner

    - name: Api Build
      stage: Build
      language: generic
      services:
        - docker
      env: 
        - REGEX='^(api\/|.travis.yml)'
      before_install:
        - git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE $REGEX || exit 0
        # Verifica se houve alguma alteração na Api no range de commits analisado pelo Travis
      script:
        - docker-compose run api rake db:setup RAILS_ENV=test
        - docker-compose run api bundle exec rails test

    - name: Client Build
      stage: Build
      language: generic
      services:
        - docker
      env: 
        - REGEX='^(client\/|.travis.yml)'
      before_install:
        - git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE $REGEX || exit 0
        # Verifica se houve alguma alteração no client no range de commits analisado
      install:
        - docker build -q -t client -f ./client/Dockerfile ./client
      script:
        - docker run client yarn test:unit
      after_script:
       - docker build -q -t client-prod -f ./client/Dockerfile.prod ./client
       # TODO deploy