version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_development
  api:
    build:
      context: ./api
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db
      DB_USER: postgres
      DB_PASSWORD: postgres
      RAILS_ENV: development
